version: "3.8"
services:
  redis:
    image: redis:latest
    ports:
      - 16379:6379
  postgres:
    image: postgres:latest
    ports:
      - 15432:5432
    volumes:
      - ./local/postgres/data/:/var/lib/postgresql/data
      - ./local/postgres/:/docker-entrypoint-initdb.d # make sure to remove all volumes files ex: rm -rf ./local/postgres/data to trigger this
    environment:
      POSTGRES_PASSWORD: mypassword
