services:
  client:
    build:
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  redis:
    image: redis:latest
    ports:
      - 16379:6379
    volumes:
      - ./server/data/services/redis/:/data
  postgres:
    image: postgres:latest
    ports:
      - 15432:5432
    volumes:
      - ./server/data/services/postgres/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
