// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/baala3/passkey-demo/auth"
	"github.com/baala3/passkey-demo/db"
	"github.com/baala3/passkey-demo/users"
	"github.com/labstack/echo/v4"
)

// Injectors from wire.go:

func NewServer() (*Server, error) {
	echoEcho := echo.New()
	webAuthn, err := auth.NewWebAuthnAPI()
	if err != nil {
		return nil, err
	}
	bunDB := db.GetDB()
	userRepository := users.UserRepository{
		DB: bunDB,
	}
	webAuthnController := auth.WebAuthnController{
		WebAuthnAPI: webAuthn,
		UserStore:   userRepository,
	}
	server := &Server{
		router:             echoEcho,
		webauthnController: webAuthnController,
	}
	return server, nil
}
