// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/baala3/passkey-demo/auth"
	"github.com/baala3/passkey-demo/users"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewServer() (*Server, error) {
	v := provideGinOptions()
	engine := gin.Default(v...)
	webAuthn, err := auth.NewWebAuthnAPI()
	if err != nil {
		return nil, err
	}
	userRepository := users.NewUserRepository()
	webAuthnController := auth.WebAuthnController{
		WebAuthnAPI: webAuthn,
		UserStore:   userRepository,
	}
	server := &Server{
		router:             engine,
		webauthnController: webAuthnController,
	}
	return server, nil
}

// wire.go:

func provideGinOptions() []gin.OptionFunc {
	return []gin.OptionFunc{}
}

var engineSet = wire.NewSet(gin.Default, provideGinOptions)
