// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/baala3/passkeys/controller"
	"github.com/baala3/passkeys/db"
	"github.com/baala3/passkeys/pkg"
	"github.com/baala3/passkeys/repository"
	"github.com/labstack/echo/v4"
)

// Injectors from wire.go:

// run `wire` to generate server and all dependencies
func NewServer() (*Server, error) {
	echoEcho := echo.New()
	webAuthn, err := pkg.NewWebAuthnAPI()
	if err != nil {
		return nil, err
	}
	bunDB := db.GetDB()
	userRepository := repository.UserRepository{
		DB: bunDB,
	}
	client := pkg.GetRedisClient()
	webAuthnSession := pkg.WebAuthnSession{
		RedisClient: client,
	}
	userSession := pkg.UserSession{
		RedisClient: client,
	}
	webAuthnAssertionsController := controller.WebAuthnAssertionsController{
		WebAuthnAPI:     webAuthn,
		UserRepository:  userRepository,
		WebAuthnSession: webAuthnSession,
		UserSession:     userSession,
	}
	webAuthnCredentialController := controller.WebAuthnCredentialController{
		WebAuthnAPI:     webAuthn,
		UserRepository:  userRepository,
		WebAuthnSession: webAuthnSession,
		UserSession:     userSession,
	}
	passwordController := controller.PasswordController{
		UserRepository: userRepository,
		UserSession:    userSession,
	}
	emailController := controller.EmailController{
		UserRepository: userRepository,
		UserSession:    userSession,
	}
	server := &Server{
		router:                       echoEcho,
		webauthnAssertionsController: webAuthnAssertionsController,
		webauthnCredentialController: webAuthnCredentialController,
		passwordController:           passwordController,
		emailController:              emailController,
	}
	return server, nil
}
